export { default as Header } from './Header'
export {default as PricingCard1} from './PricingCard1'
export {default as PricingCard} from './PricingCard2'
export { default as PricingCard3 } from './PricingCard3'
export { default as Accordion } from './Accordion'
export {default as Footer} from './Footer'